# default
config:
    test: &configDefault
        a: default_a
        b: default_b

management:
    server.port: 8081
    endpoints.web:
        base-path: /
        exposure.include: info,health,env

---
spring:
    profiles: custom

config:
    <<: *configDefault
        b: custom_b